### ISSUE TITLE
Be able to stop background tasks (if they do not seem to end)

### ISSUE THREAD

**Issue by Janmm14** [helios-decompiler/standalone-app#18]
As example just the procyon decompiler decided to stuck and now takes one cpu core fully.

An alternative would be to stop the decompilation process if a decompiler window was closed before the task finished.

**Comment by samczsun** [comment]
It's a planned feature. What I wanted to do was something like IntelliJ's background task popup, where you can click the background task text and have a popup open. However, GUIs are such a pain I've been putting it off the whole time

**Comment by Janmm14** [comment]
@samczsun You could maybe start with a simple popup, as the feature is really useful.

**Comment by samczsun** [comment]
Do you have a sample file which would hang the decompilers? I can't seem to find one at the moment

**Comment by Janmm14** [comment]
@samczsun Well I cn look whether I get it again.

**Comment by Janmm14** [comment]
Nvm the jar where I got this was not fully deobfuscated yet, I'll report back if I get an error/hang again.

**Comment by samczsun** [comment]
After almost a year, it's done!
