### ISSUE TITLE
no download links?

### ISSUE THREAD

**Issue by kingcraftingnl** [helios-decompiler/standalone-app#36]
no download links?

**Comment by samczsun** [comment]
Could try building it yourself or [this](https://ci.samczsun.com/job/helios-decompiler/job/Standalone%20App/lastReleaseBuild/)

**Comment by kingcraftingnl** [comment]
I wasnt able to Compile it it gave me some errors about Dependecys not found. And yes i did mvn install clean package

**Comment by samczsun** [comment]
Ah, that's true. You would have needed [this](https://github.com/helios-decompiler/transformer-api). My aplogies
