### ISSUE TITLE
Decompiler Only showing the Hex tab.

### ISSUE THREAD

**Issue by kingcraftingnl** [helios-decompiler/standalone-app#37]
Decompiler Only showing the Hex tab.

**Comment by samczsun** [comment]
`Ctrl-T` to open the editor context menu. No guarantees if you're using Mac. I'll re-add the right click option sometime later

**Comment by kingcraftingnl** [comment]
Ctrl-T dous not anything i have a file open ugh, Sorry hahah

**Comment by kingcraftingnl** [comment]
Using windows 10 http://prntscr.com/el3tex

**Comment by samczsun** [comment]
If ctrl-t doesn't work, you'll have to wait until I readd the right click option. Sorry

**Comment by kingcraftingnl** [comment]
a ok Any good decpiller alternatives until you add it back,
JDGui sucks and Bytecodeviewer has too many crashes :(

**Comment by samczsun** [comment]
I wouldn't recommend any of those. You could always add it in yourself for the time being, or try building a copy of Helios before the rewrite
