### ISSUE TITLE
Repository

### ISSUE THREAD

**Issue by FFY00** [helios-decompiler/standalone-app#39]
Dependence is missing from repository.

[ERROR] Failed to execute goal on project standalone-app: Could not resolve dependencies for project com.heliosdecompiler:standalone-app:jar:1.0.2: Could not find artifact com.heliosdecompiler:transformer-api:jar:2.0.3 in helios-decompiler-repo (https://repo.samczsun.com/repository/helios-decompiler/)

**Comment by Janmm14** [comment]
build the transformer-api locally with mvn install

**Comment by FFY00** [comment]
I successfully built the standalone-app from the develop branch with jenkins. I tried to add artifacts with jenkins to the master branch but it still failed. Should I run mvn install before compiling the standalone-app from the master branch?

**Comment by Janmm14** [comment]
https://github.com/helios-decompiler/transformer-api

**Comment by FFY00** [comment]
Yes, I've already built transformer-api and I'm adding the artifact. The only problem I've run into now is the transformer-api version because I've built the 2.0.5 but the project specifies the 2.0.3. Can you update the pom file? If not, I can fork and do it but the project wouldn't be always up to date. Thanks for the help.

**Comment by Janmm14** [comment]
you could checkout this commit of the transfomrer-api: https://github.com/helios-decompiler/transformer-api/commit/ae5de5bb0d5a007bd586b5b7820d5598de062d4c

**Comment by Janmm14** [comment]
Alternatively simply change the version either project it seems to be compatible

**Comment by FFY00** [comment]
It's working. Thanks for your help.
